### ISSUE TITLE
Pods get an error randomly (Remote host terminated the handshake)

### ISSUE THREAD

**Issue by realhuseyn** [linkerd/linkerd2#11333]
### What is the issue?

Some pods get an error randomly when the pod sends a request to another pod or some 3rd party URL. The error just is like: "Remote host terminated the handshake". Our microservices are written in Java and Python. 

### How can it be reproduced?

...

### Logs, error output, etc

Remote host terminated the handshake

### output of `linkerd check -o short`

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.5 but the latest stable version is 2.14.0
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.5 but the latest stable version is 2.14.0
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-7c768f978f-m9bs5 (stable-2.13.5)
	* linkerd-identity-7c95875fc8-p8h44 (stable-2.13.5)
	* linkerd-proxy-injector-665794566c-5q2j8 (stable-2.13.5)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-79c777cc58-khcdn (stable-2.13.5)
	* prometheus-677c4b4d8f-xm9x6 (stable-2.13.5)
	* tap-69df58bcd6-jmrtp (stable-2.13.5)
	* tap-injector-8cf6bc948-5ngrh (stable-2.13.5)
	* web-85bc66d4b-lh7v9 (stable-2.13.5)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √

### Environment

- v1.23.17 (EKS), v1.23.7 (On-premises Kubernetes)
- Cluster Environment - EKS, On-premises Kubernetes
- Host OS - Amazon Linux 2 (EKS), RHEL 8.8 (On-premises)
- Linkerd version - 2.11.1 (EKS), 2.13.5 (On-premises)

### Possible solution

As a solution, I disable linkerd-inject on the deployments. For example, I changed the linkerd.io/inject" annotation to disabled

### Would you like to work on fixing this bug?

yes

**Comment by familfamilzade** [comment]
I have faced the same issue

**Comment by yibrahimov** [comment]
I also have faced the same issue.

**Comment by wmorgan** [comment]
Can you paste in the full log line with some context around it please, and some more detail about whether this pod is sending the request or receiving it and the nature of the traffic?

**Comment by realhuseyn** [comment]
@wmorgan I am sharing a sample log of exceptions on the our Java Application:
    "stack_trace": "az.x.x.x.x.exception.xException: Cannot connect: Remote host terminated the handshake
     at az.x.x.x.x.service.task.x.run(x.java:100)
     at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:756)
     at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
     at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ee.x.x.x.xException: Cannot connect: Remote host terminated the handshake
     at ee.x.x.x.x.sendRequest(x.java:186)
     at ee.x.x.x.x.getAuthenticateStatus(x.java:350)
     at az.x.x.x.x.x.x.getAuthenticateStatus(x.java:109)
     at az.x.x.x.x.x.task.x.run(x.java:94)
     ... 12 common frames omitted

Roughly, our microservice sends 5000 requests to the Client on a day. 100-200 requests out of 5000 fail due to the above exception. I am even talking about 1 microservice with you, but we have other microservices that face this issue.

**Comment by realhuseyn** [comment]
For example, "linkerd-proxy" container of our microservice printed these logs:

[  4075.158678s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.233.103.13:59656
[  4135.859656s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.233.103.13:35062
[  4153.263019s]  INFO ThreadId(01) outbound:proxy{addr=10.233.103.151:42699}:forward{addr=10.233.103.151:42699}:rescue{client.addr=10.233.103.13:40176}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=endpoint 10.233.103.151:42699: error trying to connect: Connection refused (os error 111) error.sources=[error trying to connect: Connection refused (os error 111), Connection refused (os error 111)]
[  4163.267761s]  INFO ThreadId(01) outbound:proxy{addr=10.233.103.151:42699}:forward{addr=10.233.103.151:42699}:rescue{client.addr=10.233.103.13:45338}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=endpoint 10.233.103.151:42699: error trying to connect: Connection refused (os error 111) error.sources=[error trying to connect: Connection refused (os error 111), Connection refused (os error 111)]


Our microservice got the "Remote host terminated the handshake" error at 2023-09-08 11:57:29. 
"linkerd-proxy" container of the microservice printed above logs at 2023-09-08  11:57:16,  11:57:33,  11:57:43, 11:57:53.

**Comment by Turall** [comment]
Any updates about this issue?

**Comment by DavidMcLaughlin** [comment]
> For example, "linkerd-proxy" container of our microservice printed these logs:
> 
> ```
> [  4075.158678s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connection closed before message completed client.addr=10.233.103.13:59656
> [  4135.859656s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.233.103.13:35062
> [  4153.263019s]  INFO ThreadId(01) outbound:proxy{addr=10.233.103.151:42699}:forward{addr=10.233.103.151:42699}:rescue{client.addr=10.233.103.13:40176}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=endpoint 10.233.103.151:42699: error trying to connect: Connection refused (os error 111) error.sources=[error trying to connect: Connection refused (os error 111), Connection refused (os error 111)]
> [  4163.267761s]  INFO ThreadId(01) outbound:proxy{addr=10.233.103.151:42699}:forward{addr=10.233.103.151:42699}:rescue{client.addr=10.233.103.13:45338}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=endpoint 10.233.103.151:42699: error trying to connect: Connection refused (os error 111) error.sources=[error trying to connect: Connection refused (os error 111), Connection refused (os error 111)]
> ```
> 
> Our microservice got the "Remote host terminated the handshake" error at 2023-09-08 11:57:29. "linkerd-proxy" container of the microservice printed above logs at 2023-09-08 11:57:16, 11:57:33, 11:57:43, 11:57:53.

Thanks for providing additional logs. In the log message, we can see that your application is bypassing any Linkerd load balancing features by talking directly to a IP address (presumably another pod in the cluster?). Do you have your own service discovery/DNS resolution logic in your application? One interesting point is that there seems to be some retry logic 10s apart to reestablish the connection, presumably triggered by your application code. 

It could be that the pod is actually rescheduled/unhealthy in which case Linkerd is behaving as-expected. If you pass a pod IP rather than a clusterIP it will not load balance across all available endpoints. 

The question would then be - why does the problem disappear when you don't inject Linkerd? Is it possible you have exception handling logic to detect stale/old IPs and that when you inject Linkerd you are seeing a different exception in your app and it fails to trigger? This is just speculation here... ultimately to advise or debug here we would need to understand more about what is happening in the outbound pod when you see the error, and more about how you are resolving pod IPs in your client/RPC stack. 

In your case, the outbound IP that I'm assuming is a pod and would be good to inspect for status and any other errors is 10.233.103.141:42699. Obviously the value will change again if you continue to see this error - but it's the application at this address reported in the INFO logging that would be good to understand.

**Comment by realhuseyn** [comment]
Hello. I have changed these configurations on 'linkerd-config' ConfigMap:
proxy:
   inboundConnectTimeout: 180s
   outboundConnectTimeout: 180s
After these changes, our pods almost don't get "remote handshake" errors. For example, last 24 hours our pods just got this error one time.

**Comment by DavidMcLaughlin** [comment]
Glad that works but setting such a high connect timeout you may be masking other problems in your application. Feel free to file another issue if you encounter side effects with this approach.
