### ISSUE TITLE
Panic when running linkerd check with the linkerd-namespace flag set to default

### ISSUE THREAD

**Issue by dadjeibaah** [linkerd/linkerd2#2084]
This is kind of weird bug and only came across it by accident. When running Linkerd check with a namespace that doesn't have linkerd installed in it I get a panic.
```bash
➜  linkerd2 git:(master) ✗ bin/go-run cli check -l default
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-version: is running the minimum Kubernetes API version..........[ok]
linkerd-existence: control plane namespace exists..........................[ok]
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/linkerd/linkerd2/pkg/healthcheck.getPodStatuses(0xc4201a6000, 0xe, 0x13, 0x73646f702f746c)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/pkg/healthcheck/healthcheck.go:866 +0x4d6
github.com/linkerd/linkerd2/pkg/healthcheck.checkControllerRunning(0xc4201a6000, 0xe, 0x13, 0x7, 0xc4201a6000)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/pkg/healthcheck/healthcheck.go:905 +0x51
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).addLinkerdControlPlaneExistenceChecks.func2(0xc4203d7120, 0x38)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/pkg/healthcheck/healthcheck.go:433 +0x1b4
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).runCheck(0xc4205e2e80, 0xc4203d70e0, 0xc420245ac8, 0xc420321601)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/pkg/healthcheck/healthcheck.go:667 +0xa3
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).RunChecks(0xc4205e2e80, 0xc420245ac8, 0x0)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/pkg/healthcheck/healthcheck.go:640 +0x1ab
github.com/linkerd/linkerd2/cli/cmd.runChecks(0x28064e0, 0xc4200ce008, 0xc4205e2e80, 0xc4205e2d80)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/cli/cmd/check.go:179 +0x94
github.com/linkerd/linkerd2/cli/cmd.configureAndRunChecks(0xc4203bae80, 0xc420257c28, 0xc420257be0)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/cli/cmd/check.go:130 +0x76f
github.com/linkerd/linkerd2/cli/cmd.newCmdCheck.func1(0xc4205e8480, 0xc4204c3740, 0x0, 0x2, 0x0, 0x0)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/cli/cmd/check.go:62 +0x42
github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra.(*Command).execute(0xc4205e8480, 0xc4204c36a0, 0x2, 0x2, 0xc4205e8480, 0xc4204c36a0)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra/command.go:698 +0x4db
github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x31212c0, 0x0, 0x102e540, 0x23b85ed)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra/command.go:783 +0x415
github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra.(*Command).Execute(0x31212c0, 0x23c0a98, 0xc4200ae058)
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/vendor/github.com/spf13/cobra/command.go:736 +0x39
main.main()
	/Users/dennis/workspace/go/src/github.com/linkerd/linkerd2/cli/main.go:10 +0x4b
```

Pods in that namespace where from the booksapp.yaml
```bash
authors-7dbc46647b-h7hrb   2/2       Running   1          28d
books-558b45bbb-xcx8g      2/2       Running   0          28d
hello-6c666bd4f9-c6w96     3/3       Running   0          6h
hello-6c666bd4f9-s794c     3/3       Running   0          6h
hello-6c666bd4f9-tlcsk     3/3       Running   0          6h
hello-stpb9                2/2       Running   0          2m
...
```

The code that experienced the panic was here https://github.com/linkerd/linkerd2/blob/master/pkg/healthcheck/healthcheck.go#L866.

It looks like the `getPodStatuses` method assumes that all pod names will be of type `linkerd-xyz-abc-def` based off of the result of strings.Split. This method is only used when dealing  getting pod statuses from control plane pods. We probably could add a check that ensures that whatever pod we are working with in this method is indeed a control plane pod.

**Comment by klingerf** [comment]
It looks like you have a pod in that namespace ("hello-stpb9") that's spawned by a ReplicationController instead of a ReplicaSet, and that's what's causing the panic. We should update the check code to properly handle pods that don't have a replicaset ID in their name.

**Comment by dadjeibaah** [comment]
Looks like we don't see the panic anymore (visually at least) now that the linkerd check out has changed. Now when I run the same command, the check process gets stuck on this message.
```bash
- controller pod is running -- No running pods for "linkerd-controller"
```
