### ISSUE TITLE
Buffer() DeprecationWarning in Node

### ISSUE THREAD

**Issue by liquidslr** [linkerd/linkerd2#2438]
I am getting this warning, The complete stack trace is below

**Steps to reproduce:**
Run the web pack server in development mode (bin/web dev) and check the console.

```
(node:24036) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    at showFlaggedDeprecation (buffer.js:159:11)
    at new Buffer (buffer.js:174:3)
    at Hybi._handshakeResponse (/Users/gaurav/go/src/github.com/liquidslr/linkerd2/web/app/node_modules/websocket-driver/lib/websocket/driver/hybi.js:289:12)
    at Hybi.start (/Users/gaurav/go/src/github.com/liquidslr/linkerd2/web/app/node_modules/websocket-driver/lib/websocket/driver/base.js:82:25)
    at /Users/gaurav/go/src/github.com/liquidslr/linkerd2/web/app/node_modules/faye-websocket/lib/faye/websocket.js:27:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by grampelberg** [comment]
@liquidslr does bumping the websocket-driver version fix this?

**Comment by liquidslr** [comment]
tried bumping the version but it didn't help

**Comment by grampelberg** [comment]
Looks like they're using it all over the place, https://github.com/faye/websocket-driver-node/blob/master/lib/websocket/driver/hybi.js#L190. 

Could submit a PR to fix it for them, or just wait to have upstream be updated. It appears to be limited webpack-dev-server and not anything in Linkerd's code specifically.
