### ISSUE TITLE
Destination controller panics when injecting Gloo

### ISSUE THREAD

**Issue by stefanprodan** [linkerd/linkerd2#3178]
### What is the issue?

The Linkerd destination controller panics when adding Gloo to the mesh.

### How can it be reproduced?

Create gloo-system namespace:

```
kubectl create ns gloo-system
kubectl annotate namespace gloo-system linkerd.io/inject=enabled
```

Install Gloo v0.18.3 (requires Helm v2.14.0 or newer):

```
helm upgrade -i gloo gloo/gloo --version 0.18.3 --namespace gloo-system
```

Expose the linkerd dashboard with Gloo:

```bash
cat <<EOF | kubectl apply -f -
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: dashboard
  namespace: gloo-system
spec:
  upstreamSpec:
    kube:
      serviceName: linkerd-web
      serviceNamespace: linkerd
      servicePort: 8084
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: dashboard
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - '*'
    routes:
      - matcher:
          prefix: /
        routeAction:
          single:
            upstream:
              name: dashboard
              namespace: gloo-system
        routePlugins:
          transformations:
            requestTransformation:
              transformationTemplate:
                headers:
                  l5d-dst-override:
                    text: linkerd-web.linkerd.svc.cluster.local:8084
                  passthrough: {}
EOF
```

Watch the controller pod enter crash loop:

```
watch kubectl -n linkerd get pods

linkerd-controller-5fbc8965f4-prk9c       2/3     CrashLoopBackOff   3 
```

### Logs, error output, etc

kubectl -n linkerd logs deploy/linkerd-controller -c destination -f

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1190090]

goroutine 1167 [running]:
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*portPublisher).endpointsToAddresses(0xc0004cbbc0, 0xc000978ea0, 0x409a78)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/watcher/endpoints_watcher.go:396 +0xd0
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*portPublisher).updateEndpoints(0xc0004cbbc0, 0xc000978ea0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/watcher/endpoints_watcher.go:367 +0x4d
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*servicePublisher).newPortPublisher(0xc00043c240, 0xc0000001bb, 0xc0000001bb)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/watcher/endpoints_watcher.go:348 +0x451
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*servicePublisher).subscribe(0xc00043c240, 0xc0000001bb, 0x16beb00, 0xc0012be9b0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/watcher/endpoints_watcher.go:294 +0xdf
github.com/linkerd/linkerd2/controller/api/destination/watcher.(*EndpointsWatcher).Subscribe(0xc00056a270, 0xc000943ce0, 0x28, 0x16beb00, 0xc0012be9b0, 0xc000943ce0, 0x28)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/watcher/endpoints_watcher.go:136 +0x1f1
github.com/linkerd/linkerd2/controller/api/destination.(*server).Get(0xc000486be0, 0xc0012be870, 0x16d5c00, 0xc0012c2650, 0x0, 0x0)
	/go/src/github.com/linkerd/linkerd2/controller/api/destination/server.go:101 +0x307
github.com/linkerd/linkerd2-proxy-api/go/destination._Destination_Get_Handler(0x1379a00, 0xc000486be0, 0x16d4a00, 0xc0009e5a80, 0xc0012be820, 0x7fb3b4b026c0)
	/go/src/github.com/linkerd/linkerd2-proxy-api/go/destination/destination.pb.go:1823 +0x109
github.com/grpc-ecosystem/go-grpc-prometheus.StreamServerInterceptor(0x1379a00, 0xc000486be0, 0x16d4ac0, 0xc000ea57c0, 0xc0009e5a60, 0x1596f08, 0x129f720, 0xc0005d8fe0)
	/go/src/github.com/grpc-ecosystem/go-grpc-prometheus/server.go:40 +0x119
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003e46e0, 0x16d5cc0, 0xc000d60000, 0xc00128d040, 0xc00056a600, 0x221fe60, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:1060 +0x370
google.golang.org/grpc.(*Server).handleStream(0xc0003e46e0, 0x16d5cc0, 0xc000d60000, 0xc00128d040, 0x0)
	/go/src/google.golang.org/grpc/server.go:1147 +0x12aa
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000b80b20, 0xc0003e46e0, 0x16d5cc0, 0xc000d60000, 0xc00128d040)
	/go/src/google.golang.org/grpc/server.go:638 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/google.golang.org/grpc/server.go:636 +0xa1
```

#### `linkerd check` output

The check command never completes due to controller crash loop.

### Environment

- Kubernetes Version: v1.13.6-gke.13
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: stable-2.4.0

**Comment by grampelberg** [comment]
This was fixed in #3147, should go out in today's edge. I've been wondering why Gloo tries to hit the api server with `http` instead of `https`.
