### ISSUE TITLE
Meshed Zookeeper can not coordinate nodes

### ISSUE THREAD

**Issue by fsniper** [linkerd/linkerd2#3770]
### What is the issue?
Meshed Zookeeper can not coordinate nodes

### How can it be reproduced?
Start a zookeeper cluster and wait for pods to get healthy. Nodes won't accept connections.
```
helm upgrade --install zookeeper incubator/zookeeper --namespace dev --set replicaCount=3 --set podAnnotations.'linkerd\.io\/inject'=enabled
```
### Logs, error output, etc
zookeeper connection logs:
```
2019-11-28 11:57:22,693 [myid:2] - INFO  [QuorumPeer[myid=2](plain=/0.0.0.0:2181)(secure=disabled):FastLeaderElection@919] - Notification time out: 60000
2019-11-28 11:57:22,707 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1176] - Connection broken for id 1, my id = 2, error =
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$RecvWorker.run(QuorumCnxManager.java:1161)
2019-11-28 11:57:22,707 [myid:2] - WARN  [RecvWorker:1:QuorumCnxManager$RecvWorker@1179] - Interrupting SendWorker
2019-11-28 11:57:22,708 [myid:2] - INFO  [WorkerSender[myid=2]:QuorumCnxManager@430] - Have smaller server identifier, so dropping the connection: (3, 2)
2019-11-28 11:57:22,711 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1092] - Interrupted while waiting for message on queue
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.pollSendQueue(QuorumCnxManager.java:1243)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager.access$700(QuorumCnxManager.java:78)
        at org.apache.zookeeper.server.quorum.QuorumCnxManager$SendWorker.run(QuorumCnxManager.java:1080)
2019-11-28 11:57:22,711 [myid:2] - WARN  [SendWorker:1:QuorumCnxManager$SendWorker@1102] - Send worker leaving thread  id 1 my id = 2
2019-11-28 11:57:22,711 [myid:2] - INFO  [WorkerReceiver[myid=2]:FastLeaderElection@679] - Notification: 2 (message format version), 2 (n.leader), 0x0 (n.zxid), 0x1 (n.round), LOOKING (n.state), 2 (n.sid), 0x0 (n.peerEPoch), LOOKING (my state)0 (n.config version)
2019-11-28 11:57:23,171 [myid:2] - WARN  [NIOWorkerThread-4:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
2019-11-28 11:57:27,965 [myid:2] - WARN  [NIOWorkerThread-1:NIOServerCnxn@370] - Exception causing close of session 0x0: ZooKeeperServer not running
```

Zookeeper linkerd-proxy logs (no debug)
```
time="2019-11-28T11:50:40Z" level=info msg="running version stable-2.6.0"
INFO [     0.003188s] linkerd2_proxy::app::main using destination service at ControlAddr { addr: Name(NameAddr { name: "linkerd-dst.linkerd.svc.cluster.local", port: 8086 }), identity: Some("linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local") }
INFO [     0.003216s] linkerd2_proxy::app::main using identity service at Name(NameAddr { name: "linkerd-identity.linkerd.svc.cluster.local", port: 8080 })
INFO [     0.003221s] linkerd2_proxy::app::main routing on V4(127.0.0.1:4140)
INFO [     0.003225s] linkerd2_proxy::app::main proxying on V4(0.0.0.0:4143) to None
INFO [     0.003232s] linkerd2_proxy::app::main serving admin endpoint metrics on V4(0.0.0.0:4191)
INFO [     0.003235s] linkerd2_proxy::app::main protocol detection disabled for inbound ports {25, 587, 3306}
INFO [     0.003242s] linkerd2_proxy::app::main protocol detection disabled for outbound ports {25, 587, 3306}
INFO [     0.030206s] linkerd2_proxy::app::main Certified identity: default.dev.serviceaccount.identity.linkerd.cluster.local
INFO [    47.274672s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 127.0.0.1:3888)" }
INFO [    59.013361s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 127.0.0.1:3888)" }
INFO [    60.080124s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 127.0.0.1:3888)" }
INFO [    85.690594s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 127.0.0.1:3888)" }
```

tcpdump of connections via tcpdumper container:
```
12:22:57.408045 IP rls-1.rls-headless.dev.svc.cluster.local.3888 > 100.96.0.230.53736: Flags [S.], seq 3081158573, ack 3988146454, win 27760, options [mss 1400,sackOK,TS val 2594152650 ecr 3779118230,nop,wscale 9], length 0
12:22:57.408063 IP 100.96.0.230.53736 > rls-1.rls-headless.dev.svc.cluster.local.3888: Flags [.], ack 1, win 55, options [nop,nop,TS val 3779118230 ecr 2594152650], length 0
12:22:57.408148 IP 100.96.0.230.53736 > rls-1.rls-headless.dev.svc.cluster.local.3888: Flags [P.], seq 1:92, ack 1, win 55, options [nop,nop,TS val 3779118231 ecr 2594152650], length 91
12:22:57.408156 IP rls-1.rls-headless.dev.svc.cluster.local.3888 > 100.96.0.230.53736: Flags [.], ack 92, win 55, options [nop,nop,TS val 2594152651 ecr 3779118231], length 0
12:22:57.408456 IP rls-1.rls-headless.dev.svc.cluster.local.3888 > 100.96.0.230.53736: Flags [F.], seq 1, ack 92, win 55, options [nop,nop,TS val 2594152651 ecr 3779118231], length 0
12:22:57.409062 IP 100.96.0.230.53736 > rls-1.rls-headless.dev.svc.cluster.local.3888: Flags [.], ack 2, win 55, options [nop,nop,TS val 3779118231 ecr 2594152651], length 0
12:22:57.410219 IP 100.96.0.230.53736 > rls-1.rls-headless.dev.svc.cluster.local.3888: Flags [P.], seq 92:96, ack 2, win 55, options [nop,nop,TS val 3779118233 ecr 2594152651], length 4
12:22:57.410230 IP rls-1.rls-headless.dev.svc.cluster.local.3888 > 100.96.0.230.53736: Flags [R], seq 3081158575, win 0, length 0
12:23:22.978155 IP rls-1.rls-headless.dev.svc.cluster.local.45252 > 100-96-2-115.rls.dev.svc.cluster.local.3888: Flags [S], seq 949454989, win 28000, options [mss 1400,sackOK,TS val 53935857 ecr 0,nop,wscale 9], length 0
12:23:22.979020 IP rls-1.rls-headless.dev.svc.cluster.local.43444 > 100.96.0.230.3888: Flags [S], seq 1696802961, win 28000, options [mss 1400,sackOK,TS val 2594178221 ecr 0,nop,wscale 9], length 0
12:23:22.979018 IP 100-96-2-115.rls.dev.svc.cluster.local.3888 > rls-1.rls-headless.dev.svc.cluster.local.45252: Flags [S.], seq 373334373, ack 949454990, win 27760, options [mss 1358,sackOK,TS val 3701508179 ecr 53935857,nop,wscale 9], >
12:23:22.979033 IP rls-1.rls-headless.dev.svc.cluster.local.45252 > 100-96-2-115.rls.dev.svc.cluster.local.3888: Flags [.], ack 1, win 55, options [nop,nop,TS val 53935857 ecr 3701508179], length 0
12:23:22.979071 IP 100.96.0.230.3888 > rls-1.rls-headless.dev.svc.cluster.local.43444: Flags [S.], seq 3460385302, ack 1696802962, win 27760, options [mss 1400,sackOK,TS val 3779143801 ecr 2594178221,nop,wscale 9], length 0
12:23:22.979097 IP rls-1.rls-headless.dev.svc.cluster.local.43444 > 100.96.0.230.3888: Flags [.], ack 1, win 55, options [nop,nop,TS val 2594178221 ecr 3779143801], length 0
12:23:22.979228 IP rls-1.rls-headless.dev.svc.cluster.local.45252 > 100-96-2-115.rls.dev.svc.cluster.local.3888: Flags [P.], seq 1:92, ack 1, win 55, options [nop,nop,TS val 53935858 ecr 3701508179], length 91
12:23:22.979281 IP rls-1.rls-headless.dev.svc.cluster.local.45252 > 100-96-2-115.rls.dev.svc.cluster.local.3888: Flags [P.], seq 92:443, ack 1, win 55, options [nop,nop,TS val 53935858 ecr 3701508179], length 351
12:23:22.979330 IP rls-1.rls-headless.dev.svc.cluster.local.43444 > 100.96.0.230.3888: Flags [P.], seq 1:92, ack 1, win 55, options [nop,nop,TS val 2594178222 ecr 3779143801], length 91
12:23:22.979361 IP 100.96.0.230.3888 > rls-1.rls-headless.dev.svc.cluster.local.43444: Flags [.], ack 92, win 55, options [nop,nop,TS val 3779143802 ecr 2594178222], length 0
12:23:22.979416 IP rls-1.rls-headless.dev.svc.cluster.local.43444 > 100.96.0.230.3888: Flags [F.], seq 92, ack 1, win 55, options [nop,nop,TS val 2594178222 ecr 3779143802], length 0
```
(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.10
- Cluster Environment: gardener on azure
- Host OS: Core Os Stable 2079.4.0
- Linkerd version: 2.6.0

### Possible solution
Workaround: skip port 3888

**Comment by grampelberg** [comment]
As ZK is a server speaks first protocol, you've got the correct workaround. Once we have a ZK specific codec in the proxy this'll work! I'm going to close out for now.
