### ISSUE TITLE
linkerd-proxy-injector panic using linkerd edge client with linkerd stable-2.9.1 server

### ISSUE THREAD

**Issue by erwbgy** [linkerd/linkerd2#5459]
### What is the issue?

The linkerd-proxy injector Pods panic when receiving requests due to missing configuration.  This is due to using linkerd edge-20.12.4 client with linkerd stable-2.9.1 server.

### How can it be reproduced?

Follow https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/ to create Secrets using cert-manager.

Run linkerd install using edge-20.12.4 linkerd CLI (due to --ha issues with stable-2.9.1):
```
$ linkerd version
Client version: edge-20.12.4
Server version: stable-2.9.1

$ linkerd \
  install \
  --ha \
  --disable-heartbeat \
  --identity-external-issuer=true \
  --linkerd-cni-enabled \
  --restrict-dashboard-privileges
```

### Logs, error output, etc

```
$ kubectl -n linkerd logs deployment/linkerd-proxy-injector -c proxy-injector
Found 3 pods, using pod/linkerd-proxy-injector-845c8d5675-hm252
time="2020-12-30T07:59:26Z" level=info msg="running version stable-2.9.1"
time="2020-12-30T07:59:26Z" level=info msg="waiting for caches to sync"
time="2020-12-30T07:59:28Z" level=info msg="caches synced"
time="2020-12-30T07:59:28Z" level=info msg="starting admin server on :9995"
time="2020-12-30T07:59:28Z" level=info msg="listening at :8443"
time="2020-12-30T08:00:25Z" level=info msg="received admission review request 163a0d8f-f5aa-4ff1-bfd1-a476bb673516"
time="2020-12-30T08:00:25Z" level=info msg="received pod/voting-76cddcf98c-"
2020/12/30 08:00:25 http: panic serving 127.0.0.1:37642: runtime error: invalid memory address or nil pointer dereference
goroutine 185 [running]:
net/http.(*conn).serve.func1(0xc002b054a0)
        /usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x18ed5c0, 0x2c142e0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/linkerd/linkerd2/pkg/inject.(*ResourceConfig).injectPodSpec(0xc0006b6e80, 0xc00000bc20)
        /linkerd-build/pkg/inject/inject.go:569 +0x47d
github.com/linkerd/linkerd2/pkg/inject.(*ResourceConfig).GetPatch(0xc0006b6e80, 0xc001e07801, 0x1b62a2f, 0x15, 0xc001e079b8, 0xc002f82ab0, 0x23)
        /linkerd-build/pkg/inject/inject.go:270 +0x7fa
github.com/linkerd/linkerd2/controller/proxy-injector.Inject(0x1e52b20, 0xc001976340, 0xc000510780, 0xc000889040, 0x1e4bfe0, 0xc0005fa700, 0x1, 0xf34, 0xf21)
        /linkerd-build/controller/proxy-injector/webhook.go:99 +0x10ae
github.com/linkerd/linkerd2/controller/webhook.(*Server).processReq(0xc0008b20c0, 0x1e52b20, 0xc001976340, 0xc001c4e000, 0xf34, 0x1e00, 0x0)
        /linkerd-build/controller/webhook/server.go:122 +0x359
github.com/linkerd/linkerd2/controller/webhook.(*Server).serve(0xc0008b20c0, 0x1e4c960, 0xc002c56000, 0xc001a47900)
        /linkerd-build/controller/webhook/server.go:93 +0x84
net/http.HandlerFunc.ServeHTTP(0xc0008ca420, 0x1e4c960, 0xc002c56000, 0xc001a47900)
        /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc00077e540, 0x1e4c960, 0xc002c56000, 0xc001a47900)
        /usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc002b054a0, 0x1e52b20, 0xc002e31e80)
        /usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2933 +0x35c
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin PodSecurityPolicy exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin Role exists
√ cni plugin RoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes
                                                                                                                    
linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-01-01T07:33:29Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2020-12-31T07:33:35Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints
√ proxy-injector webhook has valid cert
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2020-12-31T07:33:34Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints
√ sp-validator webhook has valid cert
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2020-12-31T07:33:34Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
‼ can determine the latest version
    Get "https://versioncheck.linkerd.io/version.json?version=edge-20.12.4&uuid=50a7e4aa-79c7-42f4-a933-8b46b03cbd97&source=c
li": dial tcp: lookup versioncheck.linkerd.io on 127.0.0.1:53: no such host
    see https://linkerd.io/checks/#l5d-version-latest for hints
‼ cli is up-to-date
    unsupported version channel: edge-20.12.4
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    unsupported version channel: stable-2.9.1
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.9.1 but cli running edge-20.12.4
    see https://linkerd.io/checks/#l5d-version-control for hints

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system
√ multiple replicas of control plane pods

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.18.11
- Cluster Environment: kubeadm
- Host OS: RHEL 8.2
- Linkerd version: stable-2.9.1

### Possible solution

The panic is coming from https://github.com/linkerd/linkerd2/blob/stable-2.9.1/pkg/inject/inject.go#L569:
```
	// Configure Tracing values based on svcAddr, as it is the main toggle for tracing
	if conf.values.GetGlobal().Proxy.Trace.CollectorSvcAddr != "" {
		values.GetGlobal().Proxy.Trace = conf.trace(conf.values.GetGlobal().Proxy.Trace.CollectorSvcAddr, conf.values.GetGlobal().Proxy.Trace.CollectorSvcAccount)
	}
```
and is caused by the following being removed from the linkerd-config ConfigMap in edge:
```
    global:
      proxy:
        trace:
          collectorSvcAccount: default
          collectorSvcAddr: ""
```

### Additional context

Primarily raising this in case someone else has the same issue and searches but would like to see the value parsing be more robust.

I understand that this is not a supported configuration but you should never be too surprised at how creative your users can be :-)

**Comment by erwbgy** [comment]
Closing as:
```
‼ control plane and cli versions match
    control plane running stable-2.9.1 but cli running edge-20.12.4
    see https://linkerd.io/checks/#l5d-version-control for hints
```
makes it clear that this is not a supported configuration.
