### ISSUE TITLE
Issue with viz routes subcommand when using existing Prometheus

### ISSUE THREAD

**Issue by eubersed** [linkerd/linkerd2#5618]
### What is the issue?

It appears that several of the viz health checks are marked with both `warning` and `fatal` with respect to cluster roles and role bindings.  When Prometheus is disabled on `linkerd-viz` Helm chart install, as is the case when reusing an existing instance, the checks fail with a warning but terminate the execution of the health check chain.   In at least the case of the `linkerd viz routes` command, the health checks are utilized to create the API client.  When Prometheus is disabled, the client health check is never reached but the chain terminates on a warning and so the `CheckClientOrExit` call does not exit.  Instead it returns a `nil` client that causes a panic on use.

### How can it be reproduced?

Install `linkerd-viz` with and external Prometheus and run `linkerd viz routes`.

### Logs, error output, etc

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x237c7e9]

goroutine 1 [running]:
github.com/linkerd/linkerd2/viz/cmd.requestRouteStatsFromAPI(0x0, 0x0, 0xc0001d0370, 0xc000996880, 0x0, 0x0, 0x0, 0x0)
	/linkerd-build/viz/cmd/routes.go:109 +0x29
github.com/linkerd/linkerd2/viz/cmd.NewCmdRoutes.func1(0xc000967340, 0xc00099e7b0, 0x1, 0x3, 0x0, 0x0)
	/linkerd-build/viz/cmd/routes.go:76 +0x2da
github.com/spf13/cobra.(*Command).execute(0xc000967340, 0xc00099e780, 0x3, 0x3, 0xc000967340, 0xc00099e780)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x38f01a0, 0x0, 0x24ab340, 0xc000116058)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/linkerd-build/cli/main.go:10 +0x2d
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2021-01-28T17:35:07Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2021-01-28T20:35:00Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints
√ sp-validator webhook has valid cert
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2021-01-28T20:35:00Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints

linkerd-api
-----------
√ control plane pods are ready

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √
```

### Environment

- Kubernetes Version: 1.17.14
- Cluster Environment: GKE
- Host OS: MacOS
- Linkerd version: edge-21.1.3

### Possible solution

Removing the fatal markings on the role health checks that are also marked as warnings, and removing `linkerd-prometheus` from the `CheckForPods` slice allowed the subcommand to function.

**Comment by Pothulapati** [comment]
This is a good find. Thanks for raising this issue.

Instead of updating the existing checks to not be fatal, as most other resources are needed. These Prometheus related checks can be separated and can be marked as warn only. We can even go further and make these checks dynamic i.e only be run when there is Prometheus installed but the problem here is the measure on which we can know a Prometheus exists. The easiest would be reading the configMap and parsing it and see the value of `prometheusUrl`. This could be a bit complicated because of the absence of a go Values struct. WDYT? @adleong
