### ISSUE TITLE
Failed to rollback linkerd from stable-v2.9.2 to stable-v2.7.1

### ISSUE THREAD

**Issue by Abrishges** [linkerd/linkerd2#5639]
## Bug Report

Linkerd (v 2.x) was originally installed and upgraded using [linkerd Kustomize ](https://linkerd.io/2/tasks/customize-install/) and been able to upgrade or downgrade without any issues until v2.7.1 using the following command: 

Linkerd CLI version for upgradegrade: **stable-2.9.2**
```
Linkerd upgrade --ha -v "stable-2.x" | out-file .\linkerd.yaml -Encoding utf8 -Force;
Kubectl kustomize . | Kubectl apply -f -
```
### What is the issue?
I upgrade linkerd from 2.7.1 to 2.9.2 and run in to the [this problem](https://github.com/linkerd/linkerd2/issues/5298), needed to rollback to stable-2.7.1 version and run in to another problem

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x8 pc=0x146f905]
goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.(*proxyConfigOptions).overrideConfigs(0xc00051af20, 0xc0005067c0, 0xc000685b08)       
/linkerd-build/cli/cmd/inject.go:381 +0x415
github.com/linkerd/linkerd2/cli/cmd.(*upgradeOptions).validateAndBuild(0xc00038d7a0, 0x0, 0x0, 0x1acd720, 0xc0000d7a40, 0xc0002dd500, 0x26812a8, 0x0, 0x0, 0x0)     
 /linkerd-build/cli/cmd/upgrade.go:242 +0x294
github.com/linkerd/linkerd2/cli/cmd.upgradeRunE(0xc00038d7a0, 0x0, 0x0, 0xc0002dd500, 0x0, 0x0)      
/linkerd-build/cli/cmd/upgrade.go:184 +0x109
github.com/linkerd/linkerd2/cli/cmd.newCmdUpgrade.func1(0xc000519400, 0xc00038de00, 0x0, 0x3, 0x0, 0x0)       
/linkerd-build/cli/cmd/upgrade.go:146 +0x42
github.com/spf13/cobra.(*Command).execute(0xc000519400, 0xc00038dd70, 0x3, 0x3, 0xc000519400, 0xc00038dd70)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0x2645ea0, 0x0, 0x157bac0, 0xc000082058)    
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)     
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
/linkerd-build/cli/main.go:10 +0x34
```
Command used to rollback
Linkerd CLI version for downgrade: **stable-2.7.1**
```
Linkerd upgrade --ha -v "stable-2.7.1" | out-file .\linkerd.yaml -Encoding utf8 -Force;
Kubectl kustomize . | Kubectl apply -f -
```
I also tried `Linkerd CIL version 2.9.2` to downgrade to 2.7.1 version and resulted `imagepullbackoff `for several pods. This is because of new image are now hosted under `ghcr.io` instead of `gcr.io.`
```
linkerd-destination-6887bdc677-d8nqr      0/2     ImagePullBackOff   2          97s
linkerd-destination-6887bdc677-mdjc5      0/2     ImagePullBackOff   2          97s
linkerd-grafana-69fb96985-hl62j           2/2     Running            0          3d20h
linkerd-grafana-745bff9d97-qxmwf          0/2     ImagePullBackOff   1          97s
linkerd-heartbeat-1595973780-f8kkq        0/1     ImagePullBackOff   0          78d
linkerd-identity-57fd66c7b9-cqqtq         0/2     ImagePullBackOff   2          97s
linkerd-identity-57fd66c7b9-vv2kh         0/2     ImagePullBackOff   2          95s
linkerd-identity-844949b47c-9w6h4         2/2     Running            0          20h
linkerd-identity-844949b47c-wnmxz         2/2     Running            0          20h
linkerd-prometheus-855f8d986f-g2mw7       2/2     Running            0          3d20h
linkerd-prometheus-85787d44f8-glzt4       0/2     Pending            0          97s
linkerd-proxy-injector-5698576c6b-rf7pc   0/2     ImagePullBackOff   2          95s
linkerd-proxy-injector-5698576c6b-v7r9d   0/2     ErrImagePull       2          97s
linkerd-proxy-injector-78654cc97b-52z9f   2/2     Running            0          3d20h
linkerd-proxy-injector-78654cc97b-w24k9   2/2     Running            0          3d20h
linkerd-sp-validator-6dfc57dd6d-p8dlr     0/2     ImagePullBackOff   2          96s
linkerd-sp-validator-6dfc57dd6d-xrc4t     0/2     ImagePullBackOff   2          95s
```

```
 Normal   BackOff    17s               kubelet, aks-core-15901661-vmss000003  Back-off pulling image "ghcr.io/linkerd/proxy:stable-2.7.1"
Warning  Failed     17s               kubelet, aks-core-15901661-vmss000003  Error: ImagePullBackOff
```

### How can it be reproduced?
Use linkerd upgrade command provided by [linkerd documentation ](https://linkerd.io/2/tasks/upgrade/)to upgrade to the latest stable version 2.9.1. or 2.9.2 and verify that linkerd check shows everything is looking good. Then Change linkerd CLI to version 2.7.1 and  rollback linkerd using the same command. 

### Logs

Linkerd rollback error 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x8 pc=0x146f905]
goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.(*proxyConfigOptions).overrideConfigs(0xc00051af20, 0xc0005067c0, 0xc000685b08)       
/linkerd-build/cli/cmd/inject.go:381 +0x415
github.com/linkerd/linkerd2/cli/cmd.(*upgradeOptions).validateAndBuild(0xc00038d7a0, 0x0, 0x0, 0x1acd720, 0xc0000d7a40, 0xc0002dd500, 0x26812a8, 0x0, 0x0, 0x0)     
 /linkerd-build/cli/cmd/upgrade.go:242 +0x294
github.com/linkerd/linkerd2/cli/cmd.upgradeRunE(0xc00038d7a0, 0x0, 0x0, 0xc0002dd500, 0x0, 0x0)      
/linkerd-build/cli/cmd/upgrade.go:184 +0x109
github.com/linkerd/linkerd2/cli/cmd.newCmdUpgrade.func1(0xc000519400, 0xc00038de00, 0x0, 0x3, 0x0, 0x0)       
/linkerd-build/cli/cmd/upgrade.go:146 +0x42
github.com/spf13/cobra.(*Command).execute(0xc000519400, 0xc00038dd70, 0x3, 0x3, 0xc000519400, 0xc00038dd70)
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x467
github.com/spf13/cobra.(*Command).ExecuteC(0x2645ea0, 0x0, 0x157bac0, 0xc000082058)    
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)     
/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
/linkerd-build/cli/main.go:10 +0x34
```

#### `linkerd check` output

```text
The linkerd check after upgrade was showing that everything looked good.
```

### Environment

- Kubernetes Version: **v1.17.13**
- Cluster Environment: **AKS**
- Host OS: **Linux**
- Linkerd version: **2.9.2**

### Possible solution
Rollbacks using CLI 2.9.x from 2.9.x to 2.7.1 might be possible if we provide a way to set `proxyImage ` setting in the `linkerd-config ` configmanp or someother command as it tries to pull from wrong repo. As of 2.9.x version, images are hosted under `ghcr.io` instead of `gcr.io` .

**Comment by adleong** [comment]
Hi @Abrishges!  The panic in the 2.7.1 CLI is unfortunate and ideally we'd handle this error a bit more gracefully.  Unfortunately, Linkerd stable-2.9.x introduced a new format for storing the Linkerd configuration which means that it is not possible to roll back to a pre-2.9.0 version after upgrading to stable-2.9.x.
