### ISSUE TITLE
Linkerd-proxy connection refused/closed/reset errors

### ISSUE THREAD

**Issue by emcay** [linkerd/linkerd2#5864]
### What is the issue?

Per https://github.com/linkerd/linkerd2/issues/5331

Seeing "connection closed" errors after upgrading.

### How can it be reproduced?

Unknown, issue is persistent and disappears on downgrade (2.7.1).

### Logs, error output, etc

`INFO ThreadId(01) outbound:accept{peer.addr=REDACTED target.addr=REDACTED: linkerd2_app_core::serve: Connection closed error=Transport endpoint is not connected (os error 107)`

#### `linkerd check` output

```kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x211d154]

goroutine 1 [running]:
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).checkCertificatesConfig(0xc0008ccc30, 0xc0005cf908, 0x1031292, 0x700000000, 0xc000091d60, 0x282fd60, 0xc0005cf920)
	/private/tmp/linkerd-20200610-10558-7kjrmk/pkg/healthcheck/healthcheck.go:1443 +0x84
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).allCategories.func48(0x282fd60, 0xc0004bd4a0, 0x6fc23ac00, 0x282fd60)
	/private/tmp/linkerd-20200610-10558-7kjrmk/pkg/healthcheck/healthcheck.go:919 +0x33
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).runCheck(0xc0008ccc30, 0x2590beb, 0x10, 0xc0005cfac0, 0xc0005cfbf8, 0xc00020f900)
	/private/tmp/linkerd-20200610-10558-7kjrmk/pkg/healthcheck/healthcheck.go:1329 +0x14c
github.com/linkerd/linkerd2/pkg/healthcheck.(*HealthChecker).RunChecks(0xc0008ccc30, 0xc0005cfbf8, 0x4)
	/private/tmp/linkerd-20200610-10558-7kjrmk/pkg/healthcheck/healthcheck.go:1298 +0x298
github.com/linkerd/linkerd2/cli/cmd.runChecksTable(0x27edfe0, 0xc00010c008, 0xc0008ccc30, 0x0)
	/private/tmp/linkerd-20200610-10558-7kjrmk/cli/cmd/check.go:274 +0x12b
github.com/linkerd/linkerd2/cli/cmd.runChecks(0x27edfe0, 0xc00010c008, 0x27edfe0, 0xc00010c010, 0xc0008ccc30, 0x2582ea4, 0x5, 0x3)
	/private/tmp/linkerd-20200610-10558-7kjrmk/cli/cmd/check.go:228 +0x5b
github.com/linkerd/linkerd2/cli/cmd.configureAndRunChecks(0x27edfe0, 0xc00010c008, 0x27edfe0, 0xc00010c010, 0x0, 0x0, 0xc00021b980, 0x0, 0x0)
	/private/tmp/linkerd-20200610-10558-7kjrmk/cli/cmd/check.go:215 +0x5b1
github.com/linkerd/linkerd2/cli/cmd.newCmdCheck.func1(0xc0001bb400, 0x356a078, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/linkerd-20200610-10558-7kjrmk/cli/cmd/check.go:135 +0x62
github.com/spf13/cobra.(*Command).execute(0xc0001bb400, 0x356a078, 0x0, 0x0, 0xc0001bb400, 0x356a078)
	/private/tmp/linkerd-20200610-10558-7kjrmk/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x351dcc0, 0x0, 0x22ce8a0, 0xc000092058)
	/private/tmp/linkerd-20200610-10558-7kjrmk/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/linkerd-20200610-10558-7kjrmk/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/private/tmp/linkerd-20200610-10558-7kjrmk/cli/main.go:10 +0x2d
```

### Environment

v1.18.9-eks-d1db3c.
Linkerd 2.9.0

**Comment by adleong** [comment]
Hi @emcay!  Linkerd stable-2.10.0 has just be released which includes several changes to Linkerd's connection management.  It would be great if you could try out stable-2.10.0 and let us know if you still see this issue.

**Comment by emcay** [comment]
Thanks, unfortunately that will take us some time, I will respond back with results.

**Comment by adleong** [comment]
Hi @emcay!  Since this has been idle for a while, I'm going to close this issue.  Please feel free to re-open or file a new one when you have time!

**Comment by emcay** [comment]
Hi very sorry for the delay in the response. Just wanted to report back that 2.10.0 did indeed resolve the issue. Thanks!

**Comment by wmorgan** [comment]
W00t!
