### ISSUE TITLE
linkerd repair segfault in 2.10.0

### ISSUE THREAD

**Issue by kellycampbell** [linkerd/linkerd2#5917]
### What is the issue?

```text
$ linkerd repair
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17d910a]

goroutine 1 [running]:
github.com/linkerd/linkerd2/cli/cmd.resetVersion(0xc000240500, 0x1210, 0x1300)
	/linkerd-build/cli/cmd/repair.go:123 +0x7a
github.com/linkerd/linkerd2/cli/cmd.newCmdRepair.func1(0xc00045ab00, 0x2d55fc8, 0x0, 0x0, 0x0, 0x0)
	/linkerd-build/cli/cmd/repair.go:65 +0x469
github.com/spf13/cobra.(*Command).execute(0xc00045ab00, 0x2d55fc8, 0x0, 0x0, 0xc00045ab00, 0x2d55fc8)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x2d092a0, 0xc00018c010, 0x1, 0x1)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/linkerd-build/cli/main.go:34 +0x19f
```

### How can it be reproduced?

Running the repair command while upgrading a cluster from 2.9.2 to 2.10.0

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.9.2 but the latest stable version is 2.10.0
    see https://linkerd.io/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.9.2 but cli running stable-2.10.0
    see https://linkerd.io/checks/#l5d-version-control for hints
```

### Environment

- Kubernetes Version: v1.17.11
- Cluster Environment: kops 
- Host OS: Debian stretch
- Linkerd version: 2.10.0

### Possible solution

Using linkerd version 2.9.4, the repair command works.

### Additional context

Non-helm.

```text
$ linkerd version
Client version: stable-2.10.0
Server version: stable-2.9.2
```

**Comment by Pothulapati** [comment]
Hey @kellycampbell, Thanks for raising this issue!

I see what's happening! This is because the `linkerd-config` format changed from `2.9` to `2.10` and thus some of the expected fields were missing. I have a [change which can fix this](https://github.com/linkerd/linkerd2/commit/439c804a2d28890ba5189027414930309fb56103) **but** that means that we are upgrading to the `2.10` format even when the control-plane is still in `2.9` which would create further issues.

I think the answer to this question is to always run `linkerd repair` with the same version of the CLI that your server runs on. So, That you get a config that works with the current state (i.e 2.9.4 in this case) . Maybe we should do a better job at documenting this. WDYT @adleong
