### ISSUE TITLE
Linkerd CNI plugin breaks initContainers which need networking

### ISSUE THREAD

**Issue by tspearconquest** [linkerd/linkerd2#8100]
### What is the issue?

The container grafana-sc-datasources contained in Prometheus is an example of an initContainer which requires networking.

There is a reported issue with Prometheus [here](https://github.com/grafana/helm-charts/issues/237) for the same happening with Istio. For some reason, it seems that the prometheus team hasn't been able to find a workaround they can provide so far, so I am hoping that Linkerd can provide one for Linkerd CNI.

If I need to set --cni-log-level=debug, let me know and I'll do that and provide those logs as well.

### How can it be reproduced?

Install linkerd-cni
Install linkerd2
Install Prometheus

### Logs, error output, etc

PFB the logs for grafana-sc-datasources:
```
[2022-03-18 06:24:06] Starting collector
[2022-03-18 06:24:06] No folder annotation was provided, defaulting to k8s-sidecar-target-directory
[2022-03-18 06:24:06] Selected resource type: ('secret', 'configmap')
[2022-03-18 06:24:06] Loading incluster config ...
[2022-03-18 06:24:06] Config for cluster api at 'https://10.254.128.1:443' loaded...
[2022-03-18 06:24:06] Unique filenames will not be enforced.
[2022-03-18 06:24:06] 5xx response content will not be enabled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb6c3111730>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sidecar.py", line 124, in <module>
    main()
  File "/app/sidecar.py", line 84, in main
    list_resources(label, label_value, target_folder, request_url, request_method, request_payload,
  File "/app/resources.py", line 80, in list_resources
    ret = getattr(v1, _list_namespace[namespace][resource])(**additional_args)
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 15938, in list_namespaced_secret
    return self.list_namespaced_secret_with_http_info(namespace, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api/core_v1_api.py", line 16049, in list_namespaced_secret_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 239, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.8/site-packages/kubernetes/client/rest.py", line 212, in request
    r = self.pool_manager.request(method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 74, in request
    return self.request_encode_url(
  File "/usr/local/lib/python3.8/site-packages/urllib3/request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.254.128.1', port=443): Max retries exceeded with url: /api/v1/namespaces/mon/secrets?labelSelector=grafana_datasource (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb6c3111730>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are up-to-date

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ viz extension proxies are up-to-date

Status check results are √
```

### Environment

Kubernetes 1.19.4
Cluster environment: AKS
Host OS: Ubuntu 20.04
Linkerd version: stable-2.11.1

**Comment by alfsch** [comment]
You have the same issues with istio using istio cni plugin

**Comment by mateiidavid** [comment]
@tspearconquest do you know what kind of connection the init container is trying to make? You can probably skip the outbound ports. If I had to guess, the init container needs to connect somewhere but because connections are routed to the proxy (and there is no socket listening on the proxy port, because the proxy is not up yet) then everything sort of fails. 

Does this sound about right?

**Comment by tspearconquest** [comment]
That sounds correct. It looks like an HTTPS connection from the log output I shared above, so I tried adding the annotation `linkerd.io/skip-outbound-ports: 443`

I was thinking about it just a moment ago before I saw your comment and realized that the pods running when we switched to linkerd-cni continued to work despite not restarting them without their initcontainers, so I thought maybe an option to allow this to work and not have to skip outbound ports would be to offer an annotation that can be specified on pods where the CNI doesn't work to still force the initContainer to be injected by the proxy injector to only those pods.

**Comment by tspearconquest** [comment]
That sounds correct. It looks like an HTTPS connection from the log output I shared above, so I tried adding the annotation `linkerd.io/skip-outbound-ports: "443"` to the prometheus deployment manifest just below where we have the inject annotation, but the output is the same as before.

**Comment by tspearconquest** [comment]
I just double checked the documentation, let me try with the right annotation...

**Comment by mateiidavid** [comment]
Cool, let me know how that goes :)

**Comment by tspearconquest** [comment]
Setting the annotation properly has fixed the startup of the container, however it would be nice to see if its possible to get this working without having to skip the ports since we actually would like to see that traffic.

I have an idea and will open a new issue as a feature request.
