### ISSUE TITLE
Linkerd Viz fails to run on arm64

### ISSUE THREAD

**Issue by jeremychase** [linkerd/linkerd2#9544]
### What is the issue?

The Prometheus pod in the linkerd-viz namespace does not run successfully on arm64 and MacOS due to a panic, resulting in CrashLoopBackOff.

### How can it be reproduced?

```
kind create cluster

# Linkerd 2.12.1
linkerd install --crds | kubectl apply -f -
linkerd install | kubectl apply -f -

# Wait for Linkerd Deploys to become Ready

linkerd viz install | kubectl apply -f -
```

### Logs, error output, etc

```
$ kubectl -n linkerd-viz describe pods prometheus-58d6fd8d8d-zkfxj
Name:         prometheus-58d6fd8d8d-zkfxj
Namespace:    linkerd-viz
Priority:     0
Node:         kind-control-plane/172.18.0.4
Start Time:   Mon, 03 Oct 2022 11:54:48 -0400
Labels:       component=prometheus
              linkerd.io/control-plane-ns=linkerd
              linkerd.io/extension=viz
              linkerd.io/proxy-deployment=prometheus
              linkerd.io/workload-ns=linkerd-viz
              namespace=linkerd-viz
              pod-template-hash=58d6fd8d8d
Annotations:  linkerd.io/created-by: linkerd/proxy-injector stable-2.12.1
              linkerd.io/inject: enabled
              linkerd.io/proxy-version: stable-2.12.1
              linkerd.io/trust-root-sha256: 1d4222cd2b70c812e42318b190c5aab8ab2e5c2ca88b1dff3396926732ca0005
Status:       Running
IP:           10.244.0.9
IPs:
  IP:           10.244.0.9
Controlled By:  ReplicaSet/prometheus-58d6fd8d8d
Init Containers:
  linkerd-init:
    Container ID:  containerd://0e64515c084b50ea834c80d9a5b991d3a1142bdcb128c32c31c72ba13d6b5e21
    Image:         cr.l5d.io/linkerd/proxy-init:v2.0.0
    Image ID:      cr.l5d.io/linkerd/proxy-init@sha256:7d5e66b9e176b1ebbdd7f40b6385d1885e82c80a06f4c6af868247bb1dffe262
    Port:          <none>
    Host Port:     <none>
    Args:
      --incoming-proxy-port
      4143
      --outgoing-proxy-port
      4140
      --proxy-uid
      2102
      --inbound-ports-to-ignore
      4190,4191,4567,4568
      --outbound-ports-to-ignore
      4567,4568
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 03 Oct 2022 11:54:49 -0400
      Finished:     Mon, 03 Oct 2022 11:54:49 -0400
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  20Mi
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /run from linkerd-proxy-init-xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rvds4 (ro)
Containers:
  linkerd-proxy:
    Container ID:   containerd://ac684b861fce7c438bef80d8badfc2876462d0df8c3abec6c31375e119aa2de1
    Image:          cr.l5d.io/linkerd/proxy:stable-2.12.1
    Image ID:       cr.l5d.io/linkerd/proxy@sha256:66dab4c3194d820be938aaedcc96c9610c6de940ec2fd089ee228ecc1ba0e868
    Ports:          4143/TCP, 4191/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 03 Oct 2022 11:54:50 -0400
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:4191/live delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:4191/ready delay=2s timeout=1s period=10s #success=1 #failure=3
    Environment:
      _pod_name:                                                prometheus-58d6fd8d8d-zkfxj (v1:metadata.name)
      _pod_ns:                                                  linkerd-viz (v1:metadata.namespace)
      _pod_nodeName:                                             (v1:spec.nodeName)
      LINKERD2_PROXY_LOG:                                       warn,linkerd=info
      LINKERD2_PROXY_LOG_FORMAT:                                plain
      LINKERD2_PROXY_DESTINATION_SVC_ADDR:                      linkerd-dst-headless.linkerd.svc.cluster.local.:8086
      LINKERD2_PROXY_DESTINATION_PROFILE_NETWORKS:              10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      LINKERD2_PROXY_POLICY_SVC_ADDR:                           linkerd-policy.linkerd.svc.cluster.local.:8090
      LINKERD2_PROXY_POLICY_WORKLOAD:                           $(_pod_ns):$(_pod_name)
      LINKERD2_PROXY_INBOUND_DEFAULT_POLICY:                    all-unauthenticated
      LINKERD2_PROXY_POLICY_CLUSTER_NETWORKS:                   10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT:                   100ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT:                  1000ms
      LINKERD2_PROXY_CONTROL_LISTEN_ADDR:                       0.0.0.0:4190
      LINKERD2_PROXY_ADMIN_LISTEN_ADDR:                         0.0.0.0:4191
      LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR:                      127.0.0.1:4140
      LINKERD2_PROXY_INBOUND_LISTEN_ADDR:                       0.0.0.0:4143
      LINKERD2_PROXY_INBOUND_IPS:                                (v1:status.podIPs)
      LINKERD2_PROXY_INBOUND_PORTS:                             9090
      LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES:              svc.cluster.local.
      LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE:                  10000ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE:                10000ms
      LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION:  25,587,3306,4444,5432,6379,9300,11211
      LINKERD2_PROXY_DESTINATION_CONTEXT:                       {"ns":"$(_pod_ns)", "nodeName":"$(_pod_nodeName)"}
                                                                
      _pod_sa:                                                   (v1:spec.serviceAccountName)
      _l5d_ns:                                                  linkerd
      _l5d_trustdomain:                                         cluster.local
      LINKERD2_PROXY_IDENTITY_DIR:                              /var/run/linkerd/identity/end-entity
      LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS:                    -----BEGIN CERTIFICATE-----
                                                                MIIBiDCCAS6gAwIBAgIBATAKBggqhkjOPQQDAjAcMRowGAYDVQQDExFpZGVudGl0
                                                                eS5saW5rZXJkLjAeFw0yMjEwMDMxNTUzMDVaFw0yMzEwMDMxNTUzMjVaMBwxGjAY
                                                                BgNVBAMTEWlkZW50aXR5LmxpbmtlcmQuMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
                                                                QgAEy+XK3n/RWHgOOtdbNRVnJ3K3nEn9Sk33lkLUHdsUA2ejidjpCBkdpIW12U6i
                                                                BQNy6w40+XJuCVCbokfKA2JGD6NhMF8wDgYDVR0PAQH/BAQDAgEGMB0GA1UdJQQW
                                                                MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQW
                                                                BBTwfoalpTe0/Sw6/nPGhTI8JIwYmTAKBggqhkjOPQQDAgNIADBFAiEAg7r+/mOY
                                                                IGzSOeug4QfO+TUa0vjIAVWR1opis5RZhZoCID4H+10nDQjiTKUUfXu/84BwzXsE
                                                                A5VwjvjNu0SCqRrJ
                                                                -----END CERTIFICATE-----
                                                                
      LINKERD2_PROXY_IDENTITY_TOKEN_FILE:                       /var/run/secrets/tokens/linkerd-identity-token
      LINKERD2_PROXY_IDENTITY_SVC_ADDR:                         linkerd-identity-headless.linkerd.svc.cluster.local.:8080
      LINKERD2_PROXY_IDENTITY_LOCAL_NAME:                       $(_pod_sa).$(_pod_ns).serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_IDENTITY_SVC_NAME:                         linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_DESTINATION_SVC_NAME:                      linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_POLICY_SVC_NAME:                           linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
    Mounts:
      /var/run/linkerd/identity/end-entity from linkerd-identity-end-entity (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rvds4 (ro)
      /var/run/secrets/tokens from linkerd-identity-token (rw)
  prometheus:
    Container ID:  containerd://465093fd0982528f9df2171944838e6573616a1ec66aa8aaa4e3c345d5800e24
    Image:         prom/prometheus:v2.30.3
    Image ID:      docker.io/prom/prometheus@sha256:e9620d250b16ffe0eb9e3eac7dd76151848424c17d577632ae9ca61d1328687e
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --log.level=info
      --log.format=logfmt
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/data
      --storage.tsdb.retention.time=6h
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 03 Oct 2022 12:16:22 -0400
      Finished:     Mon, 03 Oct 2022 12:16:23 -0400
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:9090/-/healthy delay=30s timeout=30s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9090/-/ready delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from data (rw)
      /etc/prometheus/prometheus.yml from prometheus-config (ro,path="prometheus.yml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rvds4 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  prometheus-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-config
    Optional:  false
  kube-api-access-rvds4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  linkerd-proxy-init-xtables-lock:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  linkerd-identity-end-entity:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  linkerd-identity-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  26m                  default-scheduler  Successfully assigned linkerd-viz/prometheus-58d6fd8d8d-zkfxj to kind-control-plane
  Normal   Pulled     26m                  kubelet            Container image "cr.l5d.io/linkerd/proxy-init:v2.0.0" already present on machine
  Normal   Created    26m                  kubelet            Created container linkerd-init
  Normal   Started    26m                  kubelet            Started container linkerd-init
  Normal   Pulled     26m                  kubelet            Container image "cr.l5d.io/linkerd/proxy:stable-2.12.1" already present on machine
  Normal   Created    26m                  kubelet            Created container linkerd-proxy
  Normal   Pulling    26m                  kubelet            Pulling image "prom/prometheus:v2.30.3"
  Normal   Started    26m                  kubelet            Started container linkerd-proxy
  Normal   Pulled     25m                  kubelet            Successfully pulled image "prom/prometheus:v2.30.3" in 12.133074589s
  Normal   Created    25m (x3 over 25m)    kubelet            Created container prometheus
  Normal   Started    25m (x3 over 25m)    kubelet            Started container prometheus
  Normal   Pulled     25m (x3 over 25m)    kubelet            Container image "prom/prometheus:v2.30.3" already present on machine
  Warning  BackOff    62s (x133 over 25m)  kubelet            Back-off restarting failed container
```

```
$ kubectl -n linkerd-viz logs prometheus-58d6fd8d8d-jkd8t -c prometheus
level=info ts=2022-10-03T15:49:24.193Z caller=main.go:438 msg="Starting Prometheus" version="(version=2.30.3, branch=HEAD, revision=f29caccc42557f6a8ec30ea9b3c8c089391bd5df)"
level=info ts=2022-10-03T15:49:24.193Z caller=main.go:443 build_context="(go=go1.17.1, user=root@d2ac3921a8f7, date=20211005-15:57:23)"
level=info ts=2022-10-03T15:49:24.193Z caller=main.go:444 host_details="(Linux 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 prometheus-58d6fd8d8d-jkd8t (none))"
level=info ts=2022-10-03T15:49:24.193Z caller=main.go:445 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2022-10-03T15:49:24.193Z caller=main.go:446 vm_limits="(soft=unlimited, hard=unlimited)"
unexpected fault address 0xffff890bb000
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0xffff890bb000 pc=0x7e08c]

goroutine 1 [running]:
runtime.throw({0x276f4ca, 0x5})
        /usr/local/go/src/runtime/panic.go:1198 +0x54 fp=0x40007c3160 sp=0x40007c3130 pc=0x478b4
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:732 +0xbc fp=0x40007c31a0 sp=0x40007c3160 pc=0x6057c
runtime.memmove()
        /usr/local/go/src/runtime/memmove_arm64.s:84 +0x9c fp=0x40007c31b0 sp=0x40007c31b0 pc=0x7e08c
github.com/prometheus/prometheus/promql.NewActiveQueryTracker({0xffffcfb19752, 0x5}, 0x14, {0x3009b60, 0x40002bb1d0})
        /app/promql/query_logger.go:120 +0x228 fp=0x40007c3320 sp=0x40007c31b0 pc=0x1cfb868
main.main()
        /app/cmd/prometheus/main.go:474 +0x7494 fp=0x40007c3f70 sp=0x40007c3320 pc=0x1dd0224
runtime.main()
        /usr/local/go/src/runtime/proc.go:255 +0x284 fp=0x40007c3fd0 sp=0x40007c3f70 pc=0x4a144
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1133 +0x4 fp=0x40007c3fd0 sp=0x40007c3fd0 pc=0x7d904

goroutine 16 [select]:
go.opencensus.io/stats/view.(*worker).start(0x40000ae080)
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x98
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x80

goroutine 104 [select]:
github.com/prometheus/prometheus/pkg/logging.(*Deduper).run(0x40007b3640)
        /app/pkg/logging/dedupe.go:75 +0xbc
created by github.com/prometheus/prometheus/pkg/logging.Dedupe
        /app/pkg/logging/dedupe.go:61 +0xfc

goroutine 111 [chan receive]:
github.com/prometheus/prometheus/storage/remote.(*WriteStorage).run(0x4000494a00)
        /app/storage/remote/write.go:103 +0x98
created by github.com/prometheus/prometheus/storage/remote.NewWriteStorage
        /app/storage/remote/write.go:96 +0x3b0
```        

### output of `linkerd check -o short`

```
$ linkerd check
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs
√ cluster networks contains all pods

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ proxy-init container runs as root user if docker container runtime is used

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

Linkerd extensions checks
=========================

| Running viz extension check 
```

_NOTE_ The last check "Running viz extension check" never returns.

### Environment

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:21:56Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:42:59Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/arm64"}
```

```
$ kind version
kind v0.14.0 go1.18.2 darwin/arm64
```

```
$ uname -a
Darwin jeremys-mbp.lan 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 arm64
```

```
$ linkerd version
Client version: stable-2.12.1
Server version: stable-2.12.1
```

**Comment by adleong** [comment]
This looks like the same error: https://github.com/prometheus/prometheus/issues/10912 which apparently was because the docker partition was full

**Comment by jeremychase** [comment]
@adleong That was the issue; thank you!
